version: 2
before:
  hooks:
  - go mod tidy
project_name: opener
builds:
- env:
  - CGO_ENABLED=0
  goos:
  - linux
  - darwin
  goarch:
  - amd64
  - arm
  - arm64
archives:
- name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
  format: zip
  files:
  - LICENSE
  - README.md
  wrap_in_directory: false
checksum:
  name_template: 'checksums.txt'
